[package]
name = "midoku-store"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
midoku-path.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
